-- Bulk update states for nursing homes using CMS CCN → State mapping
-- This runs as a single query with JOIN - much faster than individual updates

-- Step 1: Create temporary table with CCN → State mapping
CREATE TEMP TABLE ccn_states (
  ccn TEXT PRIMARY KEY,
  state TEXT NOT NULL
);

-- Step 2: Insert mappings from a VALUES list
-- This will be generated by reading the CMS CSV
-- Format: INSERT INTO ccn_states (ccn, state) VALUES ('015004', 'AL'), ('015011', 'AL'), ...

-- Step 3: Update resources table using JOIN
UPDATE resources
SET states = ARRAY[ccn_states.state]
FROM ccn_states
WHERE
  resources.facility_id = ccn_states.ccn
  AND resources.provider_type = 'nursing_home'
  AND resources.states IS NULL;

-- Step 4: Report results
SELECT
  COUNT(*) FILTER (WHERE states IS NOT NULL) as with_states,
  COUNT(*) FILTER (WHERE states IS NULL) as without_states,
  COUNT(*) as total
FROM resources
WHERE provider_type = 'nursing_home';
